### ISSUE TITLE
Issue running CoT

### ISSUE THREAD

**Issue by cloudygoose** [pclucas14/GansFallingShort#3]
Hi, I like the paper very much, and recommended it to people in my group, thanks for the good work.
Question about the code, it seems that you implemented CoT, I try to run it using the real_data_experiments/trained_models/news/word/best_CoT_nlltest/args.json, however there's an error:

  File "main.py", line 203, in main
    avg_accs += [(fake_acc+real_acc)/2]
UnboundLocalError: local variable 'fake_acc' referenced before assignment

I guess fake_acc should not be calculated when training for CoT. Is the code ready for running CoT or does it need revision?
Thanks!

**Comment by pclucas14** [comment]
Hi @cloudygoose, 

Thanks for flagging this! There was an indentation missing. I'm fixing it now. Let me know if something else seems wrong, I'll be happy to take a look. 

-Lucas
