### ISSUE TITLE
best_mle

### ISSUE THREAD

**Issue by cp-pc** [pclucas14/GansFallingShort#6]
There is no best_mle in trained_models/news/word/.  Would you please provide the best_mle ,  thanks very much.

**Comment by pclucas14** [comment]
Hi, 

thanks for your interest in our paper. You can find the model weights [here](https://github.com/pclucas14/GansFallingShort/blob/9440a4a5ca2ca92643f437cd85492f2e62973f72/real_data_experiments/trained_models/news/news/word/best_mle/models/gen80.pth). I'll add them back to the current reposity when I have a little bit of time. 

Best, 
Lucas

**Comment by cp-pc** [comment]
thanks a lot for your help



------------------ 原始邮件 ------------------
发件人: "Lucas Caccia"<notifications@github.com>;
发送时间: 2019年10月29日(星期二) 中午1:01
收件人: "pclucas14/GansFallingShort"<GansFallingShort@noreply.github.com>;
抄送: "菜"<1061185275@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [pclucas14/GansFallingShort] best_mle (#6)




Hi,
 
thanks for your interest in our paper. You can find the model weights here. I'll add them back to the current reposity when I have a little bit of time.
 
Best,
 Lucas

**Comment by cp-pc** [comment]
Hi, 
I found a problem with the training data in Table 5 in your paper. COCO's selfbleu5 is bigger than selfbleu4. Here is the BLEU and SELF-BLEU I tested on test data of COCO.
bleu2=0.744  bleu3=0.526 bleu4=0.344 bleu5=0.222
self-bleu2=0.895 self-bleu3=0.751 self-bleu4=0.581 self-bleu5=0.422
