### ISSUE TITLE
Calculating Self-BLEU scores

### ISSUE THREAD

**Issue by hadyelsahar** [pclucas14/GansFallingShort#9]
According the Self-BLEU original paper Zhu et al. 2018, each generation is compared against all the **other** references. 

The current Self-BLEU implementation includes the selected hypothesis in the list of references. This risks inflation in the self-bleu scores as there will be always a direct match between the hypothesis and one of the references. 

https://github.com/pclucas14/GansFallingShort/blob/ecaa60a2d310f68840777318fc730e3696cf7fa1/real_data_experiments/metrics.py#L151
```
    def get_bleu(self):
        ngram = self.gram
        bleu = list()
        reference = self.get_reference()
        weight = tuple((1. / ngram for _ in range(ngram)))
        with open(self.test_data) as test_data:
            for hypothesis in test_data:
                hypothesis = nltk.word_tokenize(hypothesis)
                bleu.append(nltk.translate.bleu_score.sentence_bleu(reference, hypothesis, weight,
                                                                    smoothing_function=SmoothingFunction().method1))
        return sum(bleu) / len(bleu)
```

I understand that this is the implementation of the Texygen as is but I was wondering if
we should remove the target hypothesis from the set of references or am I missing something here? 

Thanks for the help in advance

**Comment by pclucas14** [comment]
Hi, 

thanks for raising this point. You should probably check with the original authors of the Texygen paper, but I would suggest keeping this implementation to ensure consistency with the previous literature. 

-Lucas

**Comment by hadyelsahar** [comment]
Thanks Lucas for your reply. 
I was wondering if the self-bleu numbers in the paper still make sense?

I will create an issue on the TexyGen repo. if you are interested to follow.
